{
 "title": "CoSES_Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CO2 Emissionen Gesamt",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  \"MEMAP_Totalcost[EUR]\"\nFROM memap_CoSES\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Stromeinkauf",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  \"MEMAP_Electricitybuyingprice[EUR/kWh]\"\nFROM memap_CoSES\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Stromverkauf",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  \"MEMAP_Electricitysellingprice[EUR/kWh]\"\nFROM memap_CoSES\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "MEMAP - Nachfrage Wärme und empfohlene Produktion / Zukauf",
   "type": "graph",
   "description": "Lastprofil aus Riemerling skaliert",
   "gridPos": { "h": 14, "w": 9, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Leistung (kW)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  -\"MEMAP_Systemheatdemand\" AS \"Nachfrage\",\n  \"MEMAP_CoSESEMS02OBJ01_CPROD01\" AS \"Kessel H2\",\n  \"MEMAP_CoSESEMS01OBJ01_COUPL01\" AS \"BHKW H1\"\nFROM memap_CoSES\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "MEMAP - Nachfrage Strom und empfohlene Produktion / Zukauf",
   "type": "graph",
   "description": "Lastprofil aus Riemerling skaliert",
   "gridPos": { "h": 14, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Leistung (kW)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  -\"MEMAP_Systemelectricitydemand\" AS \"Nachfrage\",\n  \"MEMAP_ElecBuy\" AS \"Strom Einkauf\",\n  \"MEMAP_ElecSell\" AS \"Strom Verkauf\"\nFROM memap_CoSES\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "abgeschlatete Zeitschritte",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  sum(\"MEMAP_CoSESEMS01OBJ01_COUPL01OFF\") OVER (ORDER BY \"timestamp\") AS \"BHKW_off\",\n  sum(\"MEMAP_CoSESEMS02OBJ01_CPROD01_OFF\") OVER (ORDER BY \"timestamp\") AS \"Kessel_off\"\nFROM memap_coses\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Kosten letzter Zeitschritt ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  sum(\"MEMAP_ElecBuy\") OVER (ORDER BY \"timestamp\") AS \"Strom Einkauf\",\n  sum(\"MEMAP_ElecSell\") OVER (ORDER BY \"timestamp\") AS \"Strom Verkauf\"\nFROM memap_coses\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Kummulierte MEMAP-Kosten (pro Simulationsrun)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "currencyEUR", "label": "kummulierte Kosten" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  \"MEMAP_Totalcost[EUR]\" AS \"kummulierte Kosten\"\nFROM memap_CoSES\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Ent- / Ladevorgänge Speicher",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "none", "label": "Ent-/Ladeleistung [kW]" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  \"MEMAP_CoSESEMS01OBJ01_STRGE01_Charge\"-\"MEMAP_CoSESEMS01OBJ01_STRGE01_Discharge\" AS \"Storage H1\",\n  \"MEMAP_CoSESEMS02OBJ01_STRGE01_Charge\"-\"MEMAP_CoSESEMS02OBJ01_STRGE01_Discharge\" AS \"Storage H2\"\nFROM memap_CoSES\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "State of Charge (SOC) des Speichers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 14 },
   "yaxes": [
    { "format": "percentunit", "label": "Ladestand" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  \"MEMAP_CoSESEMS01OBJ01_STRGE01_SOC\" AS \"SOC Storage H1\",\n  \"MEMAP_CoSESEMS02OBJ01_STRGE01_SOC\" AS \"SOC Storage H2\"\nFROM memap_CoSES\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Wärmeübertragung zwischen den Gebäuden",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  \"MEMAP_connection_FromCoSES_H1_ToCoSES_H2Frwd\" AS \"From H1 to H2\",\n  -\"MEMAP_connection_FromCoSES_H1_ToCoSES_H2Back\" AS \"From H2 to H1\"\nFROM memap_coses\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  }
 ]
}