{
 "title": "CoSES_Dashboard",
 "time": { "from": "2021-02-03T15:27:10.706Z", "to": "2021-02-03T15:45:50.439Z" },
 "panels": [
  {
   "title": "CO2 Emissionen Gesamt",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  totalco2emissions\nFROM memap_CoSES\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Strompreis",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  electricityprice_eur\nFROM memap_CoSES\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "MEMAP - Nachfrage Wärme und empfohlene Produktion / Zukauf",
   "type": "graph",
   "description": "Lastprofil aus Riemerling skaliert",
   "gridPos": { "h": 12, "w": 9, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Leistung (kW)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  memap_systemheatdemand AS \"Nachfrage\",\n  memap_CoSESems01obj01_cprod01 AS \"Kessel\"\nFROM memap_CoSES\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "MEMAP - Nachfrage Strom und empfohlene Produktion / Zukauf",
   "type": "graph",
   "description": "Lastprofil aus Riemerling skaliert",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Leistung (kW)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  memap_systemelectricitydemand AS \"Nachfrage\",\n  memap_elecbuy AS \"Strom Einkauf\",\n  memap_elecsell AS \"Strom Verkauf\"\nFROM memap_CoSES\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "abgeschlatete Zeitschritte",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  memap_cosesems01obj01_cprod01_off AS \"Kessel_off\"\nFROM memap_coses\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Kosten letzter Zeitschritt ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  sum(memap_elecbuy) OVER (ORDER BY \"timestamp\") AS \"Strom Einkauf\",\n  sum(memap_elecsell) OVER (ORDER BY \"timestamp\") AS \"Strom Verkauf\"\nFROM memap_coses\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Kummulierte MEMAP-Kosten (pro Simulationsrun)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "currencyEUR", "label": "kummulierte Kosten" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  totalcostseur AS \"kummulierte Kosten\"\nFROM memap_CoSES\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Ent- / Ladevorgänge Speicher",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "none", "label": "Ent-/Ladeleistung [kW]" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  memap_CoSESems01obj01_strge01charge-memap_CoSESems01obj01_strge01discharge AS \"Wärmespeicher\"\nFROM memap_CoSES\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "State of Charge (SOC) des Speichers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 12 },
   "yaxes": [
    { "format": "percentunit", "label": "Ladestand" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  memap_CoSESems01obj01_strge01_soc AS \"SOC Wärmespeicher\"\nFROM memap_CoSES\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  }
 ]
}