{
 "title": "CoSES_Data",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CO2 Emissionen Gesamt",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  sum(totalco2emissions) AS \"Gesamt CO2 Emissionen\"\nFROM memapon\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  last(totalco2emissions,\"timestamp\") AS \"Aktuelle CO2 Emissionen\"\nFROM memapon\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Strompreis",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  energyprice_eur\nFROM memapon\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "CoSES Haus1 - Nachfrag und empfohlene Produktion des Kessels (Wärme)",
   "type": "graph",
   "description": "Lastprofil aus Riemerling skaliert",
   "gridPos": { "h": 14, "w": 9, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestep AS \"time\",\n  heatdemand AS \"Nachfrage\",\n  cprod00 AS \"Produktion Kessel\"\nFROM memapon\nWHERE\n  $__unixEpochFilter(timestep)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "CoSES Haus1 - Nachfrag und empfohlene Produktion des Kessels (Wärme)",
   "type": "graph",
   "description": "Lastprofil aus Riemerling skaliert",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestep AS \"time\",\n  strge00charge AS \"Einspeicherung\",\n  strge00discharge AS \"Entnahme Speicher\"\nFROM memapon\nWHERE\n  $__unixEpochFilter(timestep)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Gesamtkosten",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  last(totalcostseur,\"timestamp\") AS \"totalcostseur\"\nFROM memapon\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "kummulierte MEMAP-Kosten (pro Simulationsrun(",
   "type": "graph",
   "gridPos": { "h": 15, "w": 7, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "currencyEUR", "label": "Kosten" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  totalcostseur\nFROM memapon\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Gasboiler Downtime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 7, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  cprod00_off AS \"Status\"\nFROM memapon\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "abgeschlatete Zeitschritte",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  sum(cprod00_off) AS \"currentdemand2\"\nFROM memapon\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "State of Charge (SOC) des Speichers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 7, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  strge00soc AS \"Ladestand\"\nFROM memapon\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  }
 ]
}